src/accounts/urls.py
from django.urls import path
from .import views


app_name = 'accounts'

urlpatterns = [
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('create-user/',views.register_user_view,name='register'),
    path('user/change-password/',views.changepassword,name='changepassword'),
    path('user/profile/view/', views.user_profile_view, name='user_profile'),
   

    #Users Views
    path('users/all',views.users_list,name='users'),
    path('users/<int:id>/block',views.users_block,name='userblock'),
    path('users/<int:id>/unblock',views.users_unblock,name='userunblock'),
    path('users/blocked/all',views.users_blocked_list,name='erasedusers'),


]

src/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('welcome/', views.dashboard, name='dashboard'),
    path('acceuil/', views.acceuil, name='acceuil'),
    path('calendrier/', views.calendrier, name='calendrier'),
    path('help/', views.help, name='help'),
    path('add_note/', views.add_note, name='add_note'),
    
    # Employee
    path('employees/', views.employees, name='employees'),
    path('employees/all/', views.dashboard_employees, name='employees'),
    path('beneficiaires/', views.beneficiaires, name='beneficiaires'),
    path('beneficiaire/create/', views.dashboard_beneficiaire_create, name='beneficiairecreate'),
    path('employee/create/', views.dashboard_employees_create, name='employeecreate'),
    path('employee/profile/<int:user_id>/', views.dashboard_employee_info, name='employeeinfo'),
    path('employee/profile/edit/<int:id>/', views.employee_edit_data, name='edit'),
    path('employee/profile/edit/<int:id>/form/', views.employee_edit, name='editform'),
    path('user/profile/<int:user_id>/', views.dashboard_employee_info, name='user_profile'),

    # Leave
    path('leave/apply/', views.leave_creation, name='createleave'),
    path('leaves/pending/all/', views.leaves_list, name='leaveslist'),
    path('leaves/all/', views.leaves, name='leaves'),
    path('leaves/approved/all/', views.leaves_approved_list, name='approvedleaveslist'),
    path('leaves/cancel/all/', views.cancel_leaves_list, name='canceleaveslist'),
    path('leaves/all/view/<int:id>/', views.leaves_view, name='userleaveview'),
    path('leaves/view/table/', views.view_my_leave_table, name='staffleavetable'),
    path('leave/approve/<int:id>/', views.approve_leave, name='userleaveapprove'),
    path('leave/unapprove/<int:id>/', views.unapprove_leave, name='userleaveunapprove'),
    path('leave/cancel/<int:id>/', views.cancel_leave, name='userleasvecancel'),
    path('leave/uncancel/<int:id>/', views.uncancel_leave, name='userleaveuncancel'),
    path('leaves/rejected/all/', views.leave_rejected_list, name='leavesrejected'),
    path('leave/reject/<int:id>/', views.reject_leave, name='reject'),
    path('leave/unreject/<int:id>/', views.unreject_leave, name='unreject'),

    # Tickets
    path('ticket/create/', views.ticket_creation, name='ticketcreate'),
    path('tickets/pending/all/', views.tickets_list, name='ticketslist'),
    path('tickets/all/', views.tickets, name='tickets'),
    path('tickets/approved/all/', views.tickets_approved_list, name='approvedticketslist'),
    path('tickets/cancel/all/', views.cancel_tickets_list, name='canceleticketslist'),
    path('tickets/all/view/<int:id>/', views.tickets_view, name='userticketview'),
    path('tickets/view/table/', views.view_my_ticket_table, name='stafftickettable'),
    path('ticket/approve/<int:id>/', views.approve_ticket, name='userticketapprove'),
    path('ticket/unapprove/<int:id>/', views.unapprove_ticket, name='userticketunapprove'),
    path('ticket/cancel/<int:id>/', views.cancel_ticket, name='userticketcancel'),
    path('ticket/uncancel/<int:id>/', views.uncancel_ticket, name='userticketuncancel'),
    path('tickets/rejected/all/', views.ticket_rejected_list, name='ticketsrejected'),
    path('ticket/reject/<int:id>/', views.reject_ticket, name='rejectticket'),
    path('ticket/unreject/<int:id>/', views.unreject_ticket, name='unrejectticket'),

    #---work-on-edit-view------#
    # path('bank/edit/<int:id>/',views.employee_bank_account_update,name='accountedit'),
    path('leave/apply/',views.leave_creation,name='createleave'),
    path('leaves/pending/all/',views.leaves_list,name='leaveslist'),
    path('leaves/all/',views.leaves,name='leaves'),
    path('leaves/approved/all/',views.leaves_approved_list,name='approvedleaveslist'),
    path('leaves/cancel/all/',views.cancel_leaves_list,name='canceleaveslist'),
    path('leaves/all/view/<int:id>/',views.leaves_view,name='userleaveview'),
    path('leaves/view/table/',views.view_my_leave_table,name='staffleavetable'),
    path('leave/approve/<int:id>/',views.approve_leave,name='userleaveapprove'),
    path('leave/unapprove/<int:id>/',views.unapprove_leave,name='userleaveunapprove'),
    path('leave/cancel/<int:id>/',views.cancel_leave,name='userleasvecancel'),
    path('leave/uncancel/<int:id>/',views.uncancel_leave,name='userleaveuncancel'),
    path('leaves/rejected/all/',views.leave_rejected_list,name='leavesrejected'),
    path('leave/reject/<int:id>/',views.reject_leave,name='reject'),
    path('leave/unreject/<int:id>/',views.unreject_leave,name='unreject'),
    path('dashboard/print_leave/<int:leave_id>/', views.print_leave, name='print_leave'),

    # BIRTHDAY ROUTE
    # path('birthdays/all/',views.birthday_this_month,name='birthdays'),
    path('ticket/apply/',views.ticket_creation,name='createticket'),
    path('tickets/pending/all/',views.tickets_list,name='ticketslist'),
    path('tickets/all/',views.tickets,name='tickets'),
    path('tickets/approved/all/',views.tickets_approved_list,name='approvedticketslist'),
    path('tickets/all/view/<int:id>/',views.tickets_view,name='user_ticket_view'),
    path('tickets/view/table/',views.view_my_ticket_table,name='stafftickettable'),
    path('ticket/approve/<int:id>/',views.approve_ticket,name='userticketapprove'),
    path('ticket/unapprove/<int:id>/',views.unapprove_ticket,name='userticketunapprove'),
    path('tickets/rejected/all/',views.ticket_rejected_list,name='ticketsrejected'),
    path('ticket/reject/<int:id>/', views.reject_ticket, name='reject_ticket'),
    path('ticket/unreject/<int:id>/',views.unreject_ticket,name='unreject_ticket'),
    path('dashboard/print_ticket/<int:ticket_id>/', views.print_ticket, name='print_ticket'),
    
]

src/hrsuit/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from .import views


urlpatterns = [
    path('admin/', admin.site.urls),#change url in production --> rabotecsuits.com/_&_wysiwyg-suits_empty-link_url
    path('',views.index_view,name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('dashboard/',include('dashboard.urls',namespace='dashboard')),
   
    


]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'TUNISAIR Express ADMINISTRATION'

src/employee/models.py
import datetime
from employee.utility import code_format
from django.db import models
from employee.managers import EmployeeManager
from phonenumber_field.modelfields import PhoneNumberField
from django.utils.translation import gettext as _

from django.contrib.auth.models import User
from leave.models import Leave






class Department(models.Model):


    name = models.CharField(max_length=125)
    service = models.CharField(max_length=125,null=True,blank=True)

    created = models.DateTimeField(verbose_name=_('Created'),auto_now_add=True)
    updated = models.DateTimeField(verbose_name=_('Updated'),auto_now=True)


    class Meta:
        verbose_name = _('Department')
        verbose_name_plural = _('Departments')
        ordering = ['name','created']
    
    def __str__(self):
        return self.name



class Employee(models.Model):

    MALE = 'Homme'
    FEMALE = 'Femme'
    OTHER = 'Autre'
    

    GENDER = (
    (MALE,'Homme'),
    (FEMALE,'Femme'),
    (OTHER,'Autre'),
    
    )




    PS = 'Personnel au sol'
    PNT = 'Personnel navigant technique'
    PNC = 'personnel navigant commerciale'
    

    EMPLOYEETYPE = (
    (PS,'Personnel au sol'),
    (PNT,'Personnel navigant technique'),
    (PNC,'personnel navigant commerciale'),
    
    )


    
    
    # PERSONAL DATA
    user = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    employeeid = models.CharField(verbose_name=_('Employee ID'),max_length=10,null=True,blank=True)
    image = models.FileField(_('Image De Profile '),upload_to='profiles',default='default.png',blank=True,null=True,help_text='upload image size less than 2.0MB')#work on path username-date/image
    
    firstname = models.CharField(verbose_name=_('prénom'),max_length=125,null=False,blank=False)
    lastname = models.CharField(verbose_name=_('Nom'),max_length=125,null=False,blank=False)
    email = models.EmailField(verbose_name=_('Email'),max_length=125,null=True,blank=True)
    birthday = models.DateField(verbose_name=_('Date de naissance'),blank=False,null=False)
    department =  models.ForeignKey(Department,verbose_name =_('Départment'),on_delete=models.SET_NULL,null=True,default=None)
    employeetype = models.CharField(verbose_name=_('Type '),max_length=100,default=PS,choices=EMPLOYEETYPE,blank=False,null=True)
    
   

    # app related
    is_blocked = models.BooleanField(_('Is Blocked'),help_text='button to toggle employee block and unblock',default=False)
    is_deleted = models.BooleanField(_('Is Deleted'),help_text='button to toggle employee deleted and undelete',default=False)
 
    created = models.DateTimeField(verbose_name=_('Created'),auto_now_add=True,null=True)
    updated = models.DateTimeField(verbose_name=_('Updated'),auto_now=True,null=True)


    #PLUG MANAGERS
    objects = EmployeeManager()

    
    
    class Meta:
        verbose_name = _('Employee')
        verbose_name_plural = _('Employees')
        ordering = ['-created']



    def __str__(self):
        return self.get_full_name

    

    @property
    def get_full_name(self):
        return f"{self.firstname} {self.lastname}"


    @property
    def get_age(self):
        current_year = datetime.date.today().year
        dateofbirth_year = self.birthday.year
        if dateofbirth_year:
            return current_year - dateofbirth_year
        return



    @property
    def can_apply_leave(self):
        pass





   

    





    def save(self,*args,**kwargs):
        '''
        overriding the save method - for every instance that calls the save method 
        perform this action on its employee_id
        added : March, 03 2019 - 11:08 PM

        '''
        get_id = self.employeeid #grab employee_id number from submitted form field
        data = code_format(get_id)
        self.employeeid = data #pass the new code to the employee_id as its orifinal or actual code
        super().save(*args,**kwargs) # call the parent save method
        # print(self.employeeid)

src/leave/models.py
from django.db import models
from .manager import LeaveManager
from django.utils.translation import gettext as _
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import datetime
from datetime import timedelta



# Create your models here.
Conge = 'congé'
accident = 'accident de travail'
maladie = 'maladie'
mission = 'mission'
absence = 'absence'

LEAVE_TYPE = (
    (Conge, 'congé annuel'),
    (accident,'accident de travail'),
    (maladie, 'maladie'),
    (mission, 'mission'),
    (absence, 'absence'),
)




class Leave(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    startdate = models.DateField(verbose_name=_('Date début'), help_text='Votre congé du ..', null=True, blank=False)
    enddate = models.DateField(verbose_name=_(' Date fin '), help_text='et fini à...', null=True, blank=False)
    leavetype = models.CharField(verbose_name=_(' type congé '), choices=LEAVE_TYPE, max_length=25, default='Congé annuel', null=True, blank=False)
    status = models.CharField(max_length=12, default='pending')  # pending, approved, rejected, cancelled
    is_approved = models.BooleanField(default=False)  # hide
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    created = models.DateTimeField(auto_now=False, auto_now_add=True)

    objects = LeaveManager()

    class Meta:
        verbose_name = _('Leave')
        verbose_name_plural = _('Leaves')
        ordering = ['-created']  # recent objects

    def droit(self):
        employee = self.user.employee_set.first()
        if employee and employee.employeetype == 'PS':
            defaultdays = 26
        else:
           defaultdays = 40
        return defaultdays

   

    def __str__(self):
        return '{0} - {1}'.format(self.leavetype, self.user)

    @property
    def pretty_leave(self):
        '''
        I don't like the __str__ of leave object - this is a pretty one :-)
        '''
        leave = self.leavetype
        user = self.user
        employee = user.employee_set.first().get_full_name()
        return ('{0} - {1}'.format(employee, leave))

    @property
    def leave_days(self):
        days_count = ''
        startdate = self.startdate
        enddate = self.enddate
        if startdate > enddate:
            return
        dates = (enddate - startdate)
        return dates.days

    @property
    def leave_approved(self):
        return self.is_approved == True

    @property
    def approve_leave(self):
        if not self.is_approved:
            self.is_approved = True
            self.status = 'approved'
            self.save()

    @property
    def unapprove_leave(self):
        if self.is_approved:
            self.is_approved = False
            self.status = 'pending'
            self.save()

    @property
    def leaves_cancel(self):
        if self.is_approved or not self.is_approved:
            self.is_approved = False
            self.status = 'cancelled'
            self.save()

    @property
    def reject_leave(self):
        if self.is_approved or not self.is_approved:
            self.is_approved = False
            self.status = 'rejected'
            self.save()

    @property
    def is_rejected(self):
        return self.status == 'rejected'

src/templates/_layout.html
{% load static %}

{% load humanize %}

<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<link rel="icon" type="image/png" href="{% static 'assets/img/favicon.ico'%}">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>Dashboard - TUNISAIR Express | {% block title %} {{ title }} {% endblock %}</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <meta name="author" content="Hedir zraga <Fullstack Developer/>,mail - hedirzraga@gmail.com">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Anton|Russo+One" rel="stylesheet">

    <!-- Bootstrap core CSS     -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />

    <!-- Animation library for notifications   -->
    <link href="{% static 'css/animate.min.css' %}" rel="stylesheet"/>

    <!--  Light Bootstrap Table core CSS    -->
    <link href="{% static 'css/light-bootstrap-dashboard.css' %}" rel="stylesheet"/>
    
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" rel="stylesheet">

    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="{% static 'css/demo.css' %}" rel="stylesheet" />


    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="{% static 'css/pe-icon-7-stroke.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

</head>
<body>


    <style type="text/css">

        .title-h3{
        font-weight: bold;
        font-variant: petite-caps;
    }


     .sidebar{
    -webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
     box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2); 
     transition: all 400ms ease-in;
    }
    
    .sidebar:hover{
        -webkit-box-shadow: 0 8px 17px 2px rgba(0,0,0,0.14), 0 3px 14px 2px rgba(0,0,0,0.12), 0 5px 5px -3px rgba(0,0,0,0.2);
    box-shadow: 0 8px 17px 2px rgba(0,0,0,0.14), 0 3px 14px 2px rgba(0,0,0,0.12), 0 5px 5px -3px rgba(0,0,0,0.2);
    }


    .shadow{
        box-shadow:0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
     }

     .logo {
        text-align: center; /* Alignement du contenu au centre */
    }
    
    .simple-text {
        text-decoration: none; /* Supprime la décoration du lien */
        color: #333; /* Couleur du texte */
    }
    
    .simple-text:hover {
        color: #555; /* Couleur du texte au survol */
    }
    
    .logo img {
        width: 100px; /* Largeur de l'image */
        height: auto; /* Hauteur automatique pour maintenir les proportions */
    }

    .sub-title{
        vertical-align: -webkit-baseline-middle;
        font-size: 12px;
        font-family: 'Luckiest Guy', cursive;
    }


    tr td{
        font-variant: petite-caps;
    }

    {% block stylesheet %}
     
     
    {% endblock %}
    </style>

<div class="wrapper">
    <div class="sidebar" data-color="blue" data-image="{% static 'img/plain4.jpg' %}">

    <!--

        Tip 1: you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple"
        Tip 2: you can also add an image using data-image tag

    -->

    	<div class="sidebar-wrapper">
            <div class="logo">
                <a href="#" class="simple-text">
                    <img src="{% static '/img/tnsrr.png' %}" alt="Tunisair Express Logo"style="width: 180px; height:60px;">
                </a>
            </div>
            

            <ul class="nav">
                
                
                {% if request.user.is_superuser and request.user.is_staff %}
                <li class="active">
                    <a href="{% url 'dashboard:dashboard' %}">
                        <i class="pe-7s-graph"></i>
                        <p>Dashboard</p>
                    </a>
                </li>
                {% else %}
                <li class="">
                    <a href="{% url 'dashboard:acceuil' %}">
                        <i class="pe-7s-home"></i>
                        <p>Acceuil</p>
                    </a>
                </li>
                {% endif %}
            
                
                {% if request.user.is_superuser and request.user.is_staff %}
                <li>
                    <a href="{% url 'dashboard:employeecreate' %}">
                        <i class="pe-7s-user"></i>
                        <p>Employée</p>
                    </a>
                </li>
                {% endif %}
           
            

                <li>
                    {% if request.user.is_superuser %}<a href="{% url 'dashboard:leaves' %}">{% else %}<a href="{% url 'dashboard:staffleavetable' %}"> {% endif %}
                        <i class="pe-7s-news-paper"></i>
                        <p>congés</p>
                    </a>
                </li>
                <li>
                    {% if request.user.is_superuser %}<a href="{% url 'dashboard:tickets' %}">{% else %}<a href="{% url 'dashboard:stafftickettable' %}"> {% endif %}
                        <i class="pe-7s-ticket"></i>
                        <p>Billets</p>
                    </a>
                </li>
             
                <li>
                    <a href="{% url 'dashboard:calendrier' %}">
                        <i class="pe-7s-date"></i>
                        <p>Calendrier</p>
                    </a>
                </li>
                <li> <p>_________________________</p></li>

                {% if request.user.is_superuser %}
                <li>
                    <a href="{% url 'accounts:user_profile' %}">
                        <i class="pe-7s-user"></i>
                        <p>Mon Profil</p>
                    </a>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'dashboard:user_profile' request.user.id %}">
                        <i class="pe-7s-user"></i>
                        <p>Mon Profil</p>
                    </a>
                </li>

                {% endif %}
                <li>
                    <a href="{% url 'dashboard:help' %}">
                        <i class="pe-7s-info"></i>
                        <p>aide</p>
                    </a>
                </li>
                
            </ul>
    	</div>


    </div>

    <div class="main-panel">
    <!--EVERY APP DEFINES ITS ROUTES  -->
    {% block navheader %}
        {% include 'includes/navheader_default.html' %}
    {% endblock %}
    <!-- NAVHEADER -->       

        
    <!--CONTENTS-->
    {% block content %}
    <section class="content">
        <section class="container-fluid">
              

        </section> <!-- /container -->           
     </section>
    {% endblock %}
    <!--/CONTENTS-->

        
        
    </div>
</div>


</body>



    <!--   Core JS Files   -->
    <script src="{% static 'js/jquery.3.2.1.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>

	<!--  Charts Plugin -->
	<script src="{% static 'js/chartist.min.js' %}"></script>

    <!--  Notifications Plugin    -->
    <script src="{% static 'js/bootstrap-notify.js' %}"></script>

    <!--  Google Maps Plugin    -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>

    <!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
	<script src="{% static 'js/light-bootstrap-dashboard.js' %}"></script>

	<!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
	<script src="{% static 'js/demo.js' %}"></script>

    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script type="text/javascript">
     </script>
{% block extrajs%}
<script type="text/javascript">


    function previewImage(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('.prev-holder .prev-avatar').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }

    
    $(document).ready(function(){

        $('.refresh-page').click(function(){
            /*Script refreshes the page*/
            console.log('refresh page clicked !!!');
            location.reload(true);

        });


        $( "#id_birthday,#id_dateissued,#id_startdate,#id_enddate" ).datepicker({
            dateFormat: 'yy-mm-dd'
        });


    });
    
	</script>
  {% endblock %}
</html>