src/accounts/urls.py
from django.urls import path
from .import views


app_name = 'accounts'

urlpatterns = [
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('create-user/',views.register_user_view,name='register'),
    path('user/change-password/',views.changepassword,name='changepassword'),
    path('user/profile/view/', views.user_profile_view, name='user_profile'),
   

    #Users Views
    path('users/all',views.users_list,name='users'),
    path('users/<int:id>/block',views.users_block,name='userblock'),
    path('users/<int:id>/unblock',views.users_unblock,name='userunblock'),
    path('users/blocked/all',views.users_blocked_list,name='erasedusers'),


]

src/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('welcome/', views.dashboard, name='dashboard'),
    path('acceuil/', views.acceuil, name='acceuil'),
    path('calendrier/', views.calendrier, name='calendrier'),
    path('help/', views.help, name='help'),
    path('add_note/', views.add_note, name='add_note'),
    
    # Employee
    path('employees/', views.employees, name='employees'),
    path('employees/all/', views.dashboard_employees, name='employees'),
    path('beneficiaires/', views.beneficiaires, name='beneficiaires'),
    path('beneficiaire/create/', views.dashboard_beneficiaire_create, name='beneficiairecreate'),
    path('employee/create/', views.dashboard_employees_create, name='employeecreate'),
    path('employee/profile/<int:user_id>/', views.dashboard_employee_info, name='employeeinfo'),
    path('employee/profile/edit/<int:id>/', views.employee_edit_data, name='edit'),
    path('employee/profile/edit/<int:id>/form/', views.employee_edit, name='editform'),
    path('user/profile/<int:user_id>/', views.dashboard_employee_info, name='user_profile'),

    # Leave
    path('leave/apply/', views.leave_creation, name='createleave'),
    path('leaves/pending/all/', views.leaves_list, name='leaveslist'),
    path('leaves/all/', views.leaves, name='leaves'),
    path('leaves/approved/all/', views.leaves_approved_list, name='approvedleaveslist'),
    path('leaves/cancel/all/', views.cancel_leaves_list, name='canceleaveslist'),
    path('leaves/all/view/<int:id>/', views.leaves_view, name='userleaveview'),
    path('leaves/view/table/', views.view_my_leave_table, name='staffleavetable'),
    path('leave/approve/<int:id>/', views.approve_leave, name='userleaveapprove'),
    path('leave/unapprove/<int:id>/', views.unapprove_leave, name='userleaveunapprove'),
    path('leave/cancel/<int:id>/', views.cancel_leave, name='userleasvecancel'),
    path('leave/uncancel/<int:id>/', views.uncancel_leave, name='userleaveuncancel'),
    path('leaves/rejected/all/', views.leave_rejected_list, name='leavesrejected'),
    path('leave/reject/<int:id>/', views.reject_leave, name='reject'),
    path('leave/unreject/<int:id>/', views.unreject_leave, name='unreject'),

    # Tickets
    path('ticket/create/', views.ticket_creation, name='ticketcreate'),
    path('tickets/pending/all/', views.tickets_list, name='ticketslist'),
    path('tickets/all/', views.tickets, name='tickets'),
    path('tickets/approved/all/', views.tickets_approved_list, name='approvedticketslist'),
    path('tickets/cancel/all/', views.cancel_tickets_list, name='canceleticketslist'),
    path('tickets/all/view/<int:id>/', views.tickets_view, name='userticketview'),
    path('tickets/view/table/', views.view_my_ticket_table, name='stafftickettable'),
    path('ticket/approve/<int:id>/', views.approve_ticket, name='userticketapprove'),
    path('ticket/unapprove/<int:id>/', views.unapprove_ticket, name='userticketunapprove'),
    path('ticket/cancel/<int:id>/', views.cancel_ticket, name='userticketcancel'),
    path('ticket/uncancel/<int:id>/', views.uncancel_ticket, name='userticketuncancel'),
    path('tickets/rejected/all/', views.ticket_rejected_list, name='ticketsrejected'),
    path('ticket/reject/<int:id>/', views.reject_ticket, name='rejectticket'),
    path('ticket/unreject/<int:id>/', views.unreject_ticket, name='unrejectticket'),

    #---work-on-edit-view------#
    # path('bank/edit/<int:id>/',views.employee_bank_account_update,name='accountedit'),
    path('leave/apply/',views.leave_creation,name='createleave'),
    path('leaves/pending/all/',views.leaves_list,name='leaveslist'),
    path('leaves/all/',views.leaves,name='leaves'),
    path('leaves/approved/all/',views.leaves_approved_list,name='approvedleaveslist'),
    path('leaves/cancel/all/',views.cancel_leaves_list,name='canceleaveslist'),
    path('leaves/all/view/<int:id>/',views.leaves_view,name='userleaveview'),
    path('leaves/view/table/',views.view_my_leave_table,name='staffleavetable'),
    path('leave/approve/<int:id>/',views.approve_leave,name='userleaveapprove'),
    path('leave/unapprove/<int:id>/',views.unapprove_leave,name='userleaveunapprove'),
    path('leave/cancel/<int:id>/',views.cancel_leave,name='userleasvecancel'),
    path('leave/uncancel/<int:id>/',views.uncancel_leave,name='userleaveuncancel'),
    path('leaves/rejected/all/',views.leave_rejected_list,name='leavesrejected'),
    path('leave/reject/<int:id>/',views.reject_leave,name='reject'),
    path('leave/unreject/<int:id>/',views.unreject_leave,name='unreject'),
    path('dashboard/print_leave/<int:leave_id>/', views.print_leave, name='print_leave'),

    # BIRTHDAY ROUTE
    # path('birthdays/all/',views.birthday_this_month,name='birthdays'),
    path('ticket/apply/',views.ticket_creation,name='createticket'),
    path('tickets/pending/all/',views.tickets_list,name='ticketslist'),
    path('tickets/all/',views.tickets,name='tickets'),
    path('tickets/approved/all/',views.tickets_approved_list,name='approvedticketslist'),
    path('tickets/all/view/<int:id>/',views.tickets_view,name='user_ticket_view'),
    path('tickets/view/table/',views.view_my_ticket_table,name='stafftickettable'),
    path('ticket/approve/<int:id>/',views.approve_ticket,name='userticketapprove'),
    path('ticket/unapprove/<int:id>/',views.unapprove_ticket,name='userticketunapprove'),
    path('tickets/rejected/all/',views.ticket_rejected_list,name='ticketsrejected'),
    path('ticket/reject/<int:id>/', views.reject_ticket, name='reject_ticket'),
    path('ticket/unreject/<int:id>/',views.unreject_ticket,name='unreject_ticket'),
    path('dashboard/print_ticket/<int:ticket_id>/', views.print_ticket, name='print_ticket'),
    
]

src/hrsuit/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from .import views


urlpatterns = [
    path('admin/', admin.site.urls),#change url in production --> rabotecsuits.com/_&_wysiwyg-suits_empty-link_url
    path('',views.index_view,name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('dashboard/',include('dashboard.urls',namespace='dashboard')),
   
    


]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'TUNISAIR Express ADMINISTRATION'

src/employee/models.py
import datetime
from employee.utility import code_format
from django.db import models
from employee.managers import EmployeeManager
from phonenumber_field.modelfields import PhoneNumberField
from django.utils.translation import gettext as _

from django.contrib.auth.models import User
from leave.models import Leave






class Department(models.Model):


    name = models.CharField(max_length=125)
    service = models.CharField(max_length=125,null=True,blank=True)

    created = models.DateTimeField(verbose_name=_('Created'),auto_now_add=True)
    updated = models.DateTimeField(verbose_name=_('Updated'),auto_now=True)


    class Meta:
        verbose_name = _('Department')
        verbose_name_plural = _('Departments')
        ordering = ['name','created']
    
    def __str__(self):
        return self.name



class Employee(models.Model):

    MALE = 'Homme'
    FEMALE = 'Femme'
    OTHER = 'Autre'
    

    GENDER = (
    (MALE,'Homme'),
    (FEMALE,'Femme'),
    (OTHER,'Autre'),
    
    )




    PS = 'Personnel au sol'
    PNT = 'Personnel navigant technique'
    PNC = 'personnel navigant commerciale'
    

    EMPLOYEETYPE = (
    (PS,'Personnel au sol'),
    (PNT,'Personnel navigant technique'),
    (PNC,'personnel navigant commerciale'),
    
    )


    
    
    # PERSONAL DATA
    user = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    employeeid = models.CharField(verbose_name=_('Employee ID'),max_length=10,null=True,blank=True)
    image = models.FileField(_('Image De Profile '),upload_to='profiles',default='default.png',blank=True,null=True,help_text='upload image size less than 2.0MB')#work on path username-date/image
    
    firstname = models.CharField(verbose_name=_('prénom'),max_length=125,null=False,blank=False)
    lastname = models.CharField(verbose_name=_('Nom'),max_length=125,null=False,blank=False)
    email = models.EmailField(verbose_name=_('Email'),max_length=125,null=True,blank=True)
    birthday = models.DateField(verbose_name=_('Date de naissance'),blank=False,null=False)
    department =  models.ForeignKey(Department,verbose_name =_('Départment'),on_delete=models.SET_NULL,null=True,default=None)
    employeetype = models.CharField(verbose_name=_('Type '),max_length=100,default=PS,choices=EMPLOYEETYPE,blank=False,null=True)
    
   

    # app related
    is_blocked = models.BooleanField(_('Is Blocked'),help_text='button to toggle employee block and unblock',default=False)
    is_deleted = models.BooleanField(_('Is Deleted'),help_text='button to toggle employee deleted and undelete',default=False)
 
    created = models.DateTimeField(verbose_name=_('Created'),auto_now_add=True,null=True)
    updated = models.DateTimeField(verbose_name=_('Updated'),auto_now=True,null=True)


    #PLUG MANAGERS
    objects = EmployeeManager()

    
    
    class Meta:
        verbose_name = _('Employee')
        verbose_name_plural = _('Employees')
        ordering = ['-created']



    def __str__(self):
        return self.get_full_name

    

    @property
    def get_full_name(self):
        return f"{self.firstname} {self.lastname}"


    @property
    def get_age(self):
        current_year = datetime.date.today().year
        dateofbirth_year = self.birthday.year
        if dateofbirth_year:
            return current_year - dateofbirth_year
        return



    @property
    def can_apply_leave(self):
        pass





   

    





    def save(self,*args,**kwargs):
        '''
        overriding the save method - for every instance that calls the save method 
        perform this action on its employee_id
        added : March, 03 2019 - 11:08 PM

        '''
        get_id = self.employeeid #grab employee_id number from submitted form field
        data = code_format(get_id)
        self.employeeid = data #pass the new code to the employee_id as its orifinal or actual code
        super().save(*args,**kwargs) # call the parent save method
        # print(self.employeeid)

src/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm




class UserAddForm(UserCreationForm):
	'''
	Extending UserCreationForm - with email

	'''
	email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder':'zzz@aaa.com'}))

	class Meta:
		model = User
		fields = ['username','email','password1','password2']
		

	





class UserLogin(forms.Form):
	username = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'votre adresse email'}))
	password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'votre mot de passe'}))

src/accounts/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.models import User
from employee.models import *
from .forms import UserLogin,UserAddForm



def changepassword(request):
	if not request.user.is_authenticated:
		return redirect('/')
	'''
	Please work on me -> success & error messages & style templates
	'''
	if request.method == 'POST':
		form = PasswordChangeForm(request.user, request.POST)
		if form.is_valid():
			user = form.save(commit=True)
			update_session_auth_hash(request,user)

			messages.success(request,'mot de passe changé avec succé',extra_tags = 'alert alert-success alert-dismissible show' )
			return redirect('accounts:changepassword')
		else:
			messages.error(request,'erreur, mot de passe invalide',extra_tags = 'alert alert-warning alert-dismissible show' )
			return redirect('accounts:changepassword')
			
	form = PasswordChangeForm(request.user)
	return render(request,'accounts/change_password_form.html',{'form':form})




def register_user_view(request):
	# WORK ON (MESSAGES AND UI) & extend with email field
	if request.method == 'POST':
		form = UserAddForm(data = request.POST)
		if form.is_valid():
			instance = form.save(commit = False)
			instance.save()
			username = form.cleaned_data.get("username")

			messages.success(request,'compte crée pour {0} !!!'.format(username),extra_tags = 'alert alert-success alert-dismissible show' )
			return redirect('accounts:register')
		else:
			messages.error(request,'Username ou password est invalide',extra_tags = 'alert alert-warning alert-dismissible show')
			return redirect('accounts:register')


	form = UserAddForm()
	dataset = dict()
	dataset['form'] = form
	dataset['title'] = 'register users'
	return render(request,'accounts/register.html',dataset)



def login_view(request):
    '''
    work on me - needs messages and redirects

    '''
    if request.method == 'POST':
        form = UserLogin(data=request.POST)
        if form.is_valid():
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)
            if user and user.is_active:
                login(request, user)
                return redirect('dashboard:dashboard')
            else:
                messages.error(request, 'compte est invalide', extra_tags='alert alert-error alert-dismissible show')
                return redirect('accounts:login')

    dataset = dict()
    form = UserLogin()

    dataset['form'] = form
    return render(request, 'accounts/login.html', dataset)

def user_profile_view(request):
    if request.user.is_authenticated:
        employee = Employee.objects.filter(user=request.user).first()
        if employee is not None:
            return render(request, 'accounts/user_profile_page.html', {'employee': employee})
        else:
            return HttpResponse("Aucun profil d'employé trouvé pour cet utilisateur.")
    else:
        return HttpResponse("Désolé, vous n'êtes pas authentifié pour accéder à cette page.")


def logout_view(request):
	logout(request)
	return redirect('accounts:login')


def users_list(request):
    users = User.objects.all()
    return render(request, 'accounts/users_table.html', {'users': users, 'title': 'Users List'})

def users_unblock(request,id):
	user = get_object_or_404(User,id = id)
	emp = Employee.objects.filter(user = user).first()
	emp.is_blocked = False
	emp.save()
	user.is_active = True
	user.save()

	return redirect('accounts:users')


def users_block(request,id):
	user = get_object_or_404(User,id = id)
	emp = Employee.objects.filter(user = user).first()
	emp.is_blocked = True
	emp.save()
	
	user.is_active = False
	user.save()
	
	return redirect('accounts:users')



def users_blocked_list(request):
	blocked_employees = Employee.objects.all_blocked_employees()
	return render(request,'accounts/all_deleted_users.html',{'employees':blocked_employees,'title':'blocked users list'})

src/templates/accounts/all_deleted_users.html
{% extends '_layout.html' %}
{% block title %} {{ title }} {% endblock %}


 {% block navheader %}
 	{% include 'includes/navheader_employee_app.html' %}
 {% endblock %}
        <!--CONTENTS-->
 {% block content %}
        <section class="content">

            <section class="container-fluid">
            		<section class="row">
            			<section class="col col-lg-12 text-center">
            				<h3 class="title-h3">Liste d'utilisateurs supprimés</h3>
            			</section>
            		</section>
                	<!-- TABLE -->
                		<table class="table table-striped">
							  <thead>
							    <tr>
							      <th scope="col">Username</th>
							      <th scope="col">Employé (fullname) </th>
							      <th scope="col">Départment</th>
							      <td scope="col">Action</td>
							    </tr>
							  </thead>

							  <tbody>
							  	{% for emp in employees %}
							  	<tr>
								      <td>{{emp.user.username}}</td>
								      <td>{{ emp.get_full_name }}</td>
								      <td>{{ emp.department }}</td>
								      <td>unblock</td>
							    </tr>
							   {% endfor %}
							  </tbody>
						</table>
                	

            </section> 


        </section>
 {% endblock %}

<script type="text/javascript">
{% block extrajs%}


{% endblock %}
</script>

src/templates/accounts/change_password_form.html
{% load static %}

{% load crispy_forms_tags %}

<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<link rel="icon" type="image/png" href="assets/img/favicon.ico">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title> Connexion de l'utilisateur </title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />


    <!-- Bootstrap core CSS     -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />

    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

    <link href="{% static 'css/forms_styles.css' %}" rel="stylesheet" />

</head>

<style type="text/css">
    
html,body{
    overflow: hidden;
    height: 100%;
}

.shadow{
    -webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
    box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
}

.wrapper-form-index-page{
    padding: 4%;
}


/* ------ center form -------*/
.parent-wrap{
    display: table;
    width: 100%;
    height: 100%;
}

.sub-parent-wrap{
    display:table-cell;
    vertical-align:middle;
    padding:15px;
}

/* ----- center form ---------*/

.btn-custom{
    padding: 4px 16px !important;
    background: transparent !important;
    color: #505050 !important;
    border: 2px solid #8282e6 !important;
    transition: all 400ms ease;
}

.btn-custom:hover{
   color: #565656 !important; 
}

.forgt-pass-wrp{
    margin-top: 5px;
}

.forgt-pass-wrp a {
    text-decoration: none;
}

label {
    font-weight: 100;
    font-size: 16px;
}


h3{
    font-weight: 100 !important;
    font-size: 25px;
}



 #override-start{
    background:none !important;
    top: 35% !important;
    right:13px;
    color:#000;
    font-size: 24px;

}

.alert-warning{
    background:#fd7b7b;
}

.alert-success {
    background-color: #82b72a;
}

.alert-success,.alert-warning{
    font-size:16px;
}


</style>

<body>
<section class="parent-wrap">


  <section class="sub-parent-wrap">

    <section class="container">
      <section class="row">
        <section class="col col-sm-12">
                  {% if  messages %}
                                    {% for message in messages %}
                                     <div {% if message.tags %} class="{{ message.tags}}"{% endif %}>
                                         {{ message }}
                                         <button type="button" class="close" id = "override-start"data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                                         </button>
                                     </div>
                      {% endfor %}
                  {% endif %}
        </section>
      </section>
          <section class="row">

             <div class="col-lg-6 col-lg-offset-3">
                <div class="wrapper-form-index-page shadow">
                    <div class="row text-center">
                        <h3 class="title-h3">Formulaire (changer votre mot de passe)</h3>
                    </div>

                     <form action="" method="POST" id="login_form">
                        {% csrf_token %}
                        {{ form | crispy}}
                        <button  type="submit" class="btn btn-primary btn-lg btn-block btn-custom">Changer le mot de passe</button>
                     </form>

                     <section class="container" style="margin-top: 1rem;">
                       <div class="row">
                         <p> Allez à<a href="{% url 'dashboard:dashboard' %}" style="color:#ae6cff;">dashboard</a></p>
                       </div>
                     </section>

                </div>
             </div>
        
          </section>
    </section><!-- container-->
  </section>
</section>

</body>
    <!--   Core JS Files   -->
  <script src="{% static 'js/jquery.3.2.1.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>


<script type="text/javascript">
    $(document).ready(function(){
      

    });

</script>


</html>

src/templates/accounts/user_profile_page.html
{% extends '_layout.html' %}

{% block title %}Profil - {{ user.username }}{% endblock %}

{% block stylesheet %}
<style>
    .profile-container {
        max-width: 1200px;
        margin: 0 auto;
        padding: 2rem;
    }

    .profile-header {
        display: flex;
        align-items: center;
        gap: 2rem;
        margin-bottom: 2rem;
        padding: 2rem;
        background: #f8f9fa;
        border-radius: 10px;
        box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }

    .profile-image {
        width: 150px;
        height: 150px;
        border-radius: 50%;
        object-fit: cover;
        border: 3px solid #4ECDC4;
    }

    .profile-info {
        flex: 1;
    }

    .profile-info h1 {
        color: #333;
        margin-bottom: 0.5rem;
    }

    .profile-info h4 {
        color: #666;
        margin-bottom: 1rem;
    }

    .profile-section {
        background: white;
        border-radius: 10px;
        padding: 1.5rem;
        margin-bottom: 1.5rem;
        box-shadow: 0 2px 4px rgba(0,0,0,0.05);
    }

    .profile-section h3 {
        color: #333;
        margin-bottom: 1rem;
        border-bottom: 2px solid #4ECDC4;
        padding-bottom: 0.5rem;
    }

    .profile-section ul {
        list-style: none;
        padding: 0;
    }

    .profile-section li {
        margin-bottom: 0.8rem;
        display: flex;
        align-items: center;
        gap: 0.5rem;
    }

    .profile-section i {
        color: #4ECDC4;
    }

    .badge {
        padding: 0.5rem 1rem;
        border-radius: 20px;
        font-size: 0.9rem;
        margin-right: 0.5rem;
    }

    .badge-primary {
        background-color: #4ECDC4;
        color: white;
    }

    .badge-secondary {
        background-color: #f8f9fa;
        color: #666;
    }

    @media (max-width: 768px) {
        .profile-header {
            flex-direction: column;
            text-align: center;
            gap: 1rem;
        }
        .profile-image {
            margin: 0 auto;
        }
    }
</style>
{% endblock %}

{% block content %}
<div class="profile-container">
    <div class="profile-header">
        <img src="{{ emp.image.url if emp and emp.image else 'https://via.placeholder.com/150' }}" alt="{{ user.username }}" class="profile-image">
        <div class="profile-info">
            <h1>{{ user.username }}</h1>
            <h4>{{ emp.firstname if emp else 'Informations non renseignées' }}</h4>
            <div class="employee-type">
                <span class="badge badge-primary">{{ emp.get_employeetype_display if emp else 'Non défini' }}</span>
            </div>
        </div>
    </div>

    {% if request.user.is_superuser %}
    <div class="profile-section">
        <h3>Gestion du Profil</h3>
        <form method="POST" enctype="multipart/form-data" class="profile-form">
            {% csrf_token %}
            <div class="form-group">
                {{ form.firstname.label_tag }}
                {{ form.firstname }}
            </div>
            <div class="form-group">
                {{ form.lastname.label_tag }}
                {{ form.lastname }}
            </div>
            <div class="form-group">
                {{ form.birthday.label_tag }}
                {{ form.birthday }}
            </div>
            <div class="form-group">
                {{ form.department.label_tag }}
                {{ form.department }}
            </div>
            <div class="form-group">
                {{ form.image.label_tag }}
                {{ form.image }}
            </div>
            <div class="form-group">
                {{ form.employeetype.label_tag }}
                {{ form.employeetype }}
            </div>
            <div class="form-group">
                {{ form.is_blocked.label_tag }}
                {{ form.is_blocked }}
            </div>
            <div class="form-group">
                {{ form.is_deleted.label_tag }}
                {{ form.is_deleted }}
            </div>
            <button type="submit" class="btn btn-primary">Enregistrer</button>
        </form>
    </div>
    {% else %}
    <div class="profile-section">
        <h3>Informations de Contact</h3>
        <ul>
            <li><i class="pe-7s-mail"></i> {{ user.email }}</li>
            <li><i class="pe-7s-user"></i> {{ emp.firstname }} {{ emp.lastname }}</li>
            <li><i class="pe-7s-date"></i> Date de naissance : {{ emp.birthday|date:"d/m/Y" }}</li>
            <li><i class="pe-7s-home"></i> Département : {{ emp.department.name }}</li>
        </ul>
    </div>

    <div class="profile-section">
        <h3>Statut</h3>
        <ul>
            <li><i class="pe-7s-check"></i> Compte : {% if user.is_active %}<span class="badge badge-success">Actif</span>{% else %}<span class="badge badge-danger">Inactif</span>{% endif %}</li>
            <li><i class="pe-7s-unlock"></i> Statut : {% if emp.is_blocked %}<span class="badge badge-warning">Bloqué</span>{% else %}<span class="badge badge-success">Débloqué</span>{% endif %}</li>
            <li><i class="pe-7s-trash"></i> Suppression : {% if emp.is_deleted %}<span class="badge badge-danger">Supprimé</span>{% else %}<span class="badge badge-success">Actif</span>{% endif %}</li>
        </ul>
    </div>

    <div class="profile-section">
        <h3>Activité</h3>
        <ul>
            <li><i class="pe-7s-clock"></i> Créé le : {{ emp.created|date:"d/m/Y H:i" }}</li>
            <li><i class="pe-7s-refresh-2"></i> Mis à jour le : {{ emp.updated|date:"d/m/Y H:i" }}</li>
        </ul>
    </div>
    {% endif %}
</div>
{% endblock %}

src/templates/accounts/users_table.html
{% extends '_layout.html' %}

{% block title %} {{ title }} {% endblock %}

{% block navheader %}
  {% include 'includes/navheader_employee_app.html' %}
{% endblock %}

{% block stylesheet %}

    /* your stylesheet code here */

{% endblock %}

{% block content %}
    <section class="content">

        <section class="container-fluid">
            <!-- TABLE -->
            <div class="table-shadow">
                <div class="text-center table-description">
                    <h4 class="title-h3">Utilisateurs</h4>
                </div>
                
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Username </th>
                            <th scope="col">Statut</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>

                    <tbody>
					{% for user in users %}
						<tr>
							<td>{{ user.username }}</td>
							{% if user.is_active %}
							<td>active</td>
							{% else %}
							<td>inactive</td>
							{% endif %}

							{%  if user.is_active and user.is_superuser %}
							<!-- Admin cannot block self -->
							<td style="font-style:italic;">(admin)</td>
							{% elif user.is_active %}
							<td><a href="{% url 'accounts:userblock' user.id %}" title="block user"><i class="pe-7s-unlock"></i></a></td>
							{% else %}
							<td><a href="{% url 'accounts:userunblock' user.id %}" title="unblock user"><i class="pe-7s-lock"></i></a></td>
							{% endif %}

							
						</tr>
						{% empty %}
						<tr>
							<td colspan="3">Aucun utilisateur trouvé.</td>
						</tr>
						{% endfor %}
                    </tbody>
                </table>
            </div>
            <!-- /TABLE -->

        </section> <!-- /container --> 


    </section>
{% endblock %}

<script type="text/javascript">
{% block extrajs%}
    /* your javascript code here */
{% endblock %}
</script>