src/accounts/urls.py
from django.urls import path
from .import views


app_name = 'accounts'

urlpatterns = [
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('create-user/',views.register_user_view,name='register'),
    path('user/change-password/',views.changepassword,name='changepassword'),
    path('user/profile/view/', views.user_profile_view, name='user_profile'),
   

    #Users Views
    path('users/all',views.users_list,name='users'),
    path('users/<int:id>/block',views.users_block,name='userblock'),
    path('users/<int:id>/unblock',views.users_unblock,name='userunblock'),
    path('users/blocked/all',views.users_blocked_list,name='erasedusers'),


]

src/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('welcome/', views.dashboard, name='dashboard'),
    path('acceuil/', views.acceuil, name='acceuil'),
    path('calendrier/', views.calendrier, name='calendrier'),
    path('help/', views.help, name='help'),
    path('add_note/', views.add_note, name='add_note'),
    
    # Employee
    path('employees/', views.employees, name='employees'),
    path('employees/all/', views.dashboard_employees, name='employees'),
    path('beneficiaires/', views.beneficiaires, name='beneficiaires'),
    path('beneficiaire/create/', views.dashboard_beneficiaire_create, name='beneficiairecreate'),
    path('employee/create/', views.dashboard_employees_create, name='employeecreate'),
    path('employee/profile/<int:user_id>/', views.dashboard_employee_info, name='employeeinfo'),
    path('employee/profile/edit/<int:id>/', views.employee_edit_data, name='edit'),
    path('employee/profile/edit/<int:id>/form/', views.employee_edit, name='editform'),
    path('user/profile/<int:user_id>/', views.dashboard_employee_info, name='user_profile'),

    # Leave
    path('leave/apply/', views.leave_creation, name='createleave'),
    path('leaves/pending/all/', views.leaves_list, name='leaveslist'),
    path('leaves/all/', views.leaves, name='leaves'),
    path('leaves/approved/all/', views.leaves_approved_list, name='approvedleaveslist'),
    path('leaves/cancel/all/', views.cancel_leaves_list, name='canceleaveslist'),
    path('leaves/all/view/<int:id>/', views.leaves_view, name='userleaveview'),
    path('leaves/view/table/', views.view_my_leave_table, name='staffleavetable'),
    path('leave/approve/<int:id>/', views.approve_leave, name='userleaveapprove'),
    path('leave/unapprove/<int:id>/', views.unapprove_leave, name='userleaveunapprove'),
    path('leave/cancel/<int:id>/', views.cancel_leave, name='userleasvecancel'),
    path('leave/uncancel/<int:id>/', views.uncancel_leave, name='userleaveuncancel'),
    path('leaves/rejected/all/', views.leave_rejected_list, name='leavesrejected'),
    path('leave/reject/<int:id>/', views.reject_leave, name='reject'),
    path('leave/unreject/<int:id>/', views.unreject_leave, name='unreject'),

    # Tickets
    path('ticket/create/', views.ticket_creation, name='ticketcreate'),
    path('tickets/pending/all/', views.tickets_list, name='ticketslist'),
    path('tickets/all/', views.tickets, name='tickets'),
    path('tickets/approved/all/', views.tickets_approved_list, name='approvedticketslist'),
    path('tickets/cancel/all/', views.cancel_tickets_list, name='canceleticketslist'),
    path('tickets/all/view/<int:id>/', views.tickets_view, name='userticketview'),
    path('tickets/view/table/', views.view_my_ticket_table, name='stafftickettable'),
    path('ticket/approve/<int:id>/', views.approve_ticket, name='userticketapprove'),
    path('ticket/unapprove/<int:id>/', views.unapprove_ticket, name='userticketunapprove'),
    path('ticket/cancel/<int:id>/', views.cancel_ticket, name='userticketcancel'),
    path('ticket/uncancel/<int:id>/', views.uncancel_ticket, name='userticketuncancel'),
    path('tickets/rejected/all/', views.ticket_rejected_list, name='ticketsrejected'),
    path('ticket/reject/<int:id>/', views.reject_ticket, name='rejectticket'),
    path('ticket/unreject/<int:id>/', views.unreject_ticket, name='unrejectticket'),

    #---work-on-edit-view------#
    # path('bank/edit/<int:id>/',views.employee_bank_account_update,name='accountedit'),
    path('leave/apply/',views.leave_creation,name='createleave'),
    path('leaves/pending/all/',views.leaves_list,name='leaveslist'),
    path('leaves/all/',views.leaves,name='leaves'),
    path('leaves/approved/all/',views.leaves_approved_list,name='approvedleaveslist'),
    path('leaves/cancel/all/',views.cancel_leaves_list,name='canceleaveslist'),
    path('leaves/all/view/<int:id>/',views.leaves_view,name='userleaveview'),
    path('leaves/view/table/',views.view_my_leave_table,name='staffleavetable'),
    path('leave/approve/<int:id>/',views.approve_leave,name='userleaveapprove'),
    path('leave/unapprove/<int:id>/',views.unapprove_leave,name='userleaveunapprove'),
    path('leave/cancel/<int:id>/',views.cancel_leave,name='userleasvecancel'),
    path('leave/uncancel/<int:id>/',views.uncancel_leave,name='userleaveuncancel'),
    path('leaves/rejected/all/',views.leave_rejected_list,name='leavesrejected'),
    path('leave/reject/<int:id>/',views.reject_leave,name='reject'),
    path('leave/unreject/<int:id>/',views.unreject_leave,name='unreject'),
    path('dashboard/print_leave/<int:leave_id>/', views.print_leave, name='print_leave'),

    # BIRTHDAY ROUTE
    # path('birthdays/all/',views.birthday_this_month,name='birthdays'),
    path('ticket/apply/',views.ticket_creation,name='createticket'),
    path('tickets/pending/all/',views.tickets_list,name='ticketslist'),
    path('tickets/all/',views.tickets,name='tickets'),
    path('tickets/approved/all/',views.tickets_approved_list,name='approvedticketslist'),
    path('tickets/all/view/<int:id>/',views.tickets_view,name='user_ticket_view'),
    path('tickets/view/table/',views.view_my_ticket_table,name='stafftickettable'),
    path('ticket/approve/<int:id>/',views.approve_ticket,name='userticketapprove'),
    path('ticket/unapprove/<int:id>/',views.unapprove_ticket,name='userticketunapprove'),
    path('tickets/rejected/all/',views.ticket_rejected_list,name='ticketsrejected'),
    path('ticket/reject/<int:id>/', views.reject_ticket, name='reject_ticket'),
    path('ticket/unreject/<int:id>/',views.unreject_ticket,name='unreject_ticket'),
    path('dashboard/print_ticket/<int:ticket_id>/', views.print_ticket, name='print_ticket'),
    
]

src/hrsuit/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from .import views


urlpatterns = [
    path('admin/', admin.site.urls),#change url in production --> rabotecsuits.com/_&_wysiwyg-suits_empty-link_url
    path('',views.index_view,name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('dashboard/',include('dashboard.urls',namespace='dashboard')),
   
    


]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'TUNISAIR Express ADMINISTRATION'

src/templates/includes/home.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<link rel="icon" type="image/png" href="assets/img/favicon.ico">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title> Gestion des congés et billets à tarifs réduit - bienvenue à notre site</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
  <meta name="viewport" content="width=device-width" />
  <!-- Bootstrap core CSS     -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
  <link href="{% static 'css/pe-icon-7-stroke.css' %}" rel="stylesheet" />


  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Anton|Russo+One" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Luckiest+Guy" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Alice" rel="stylesheet">
  



</head>
<body>

    <style type="text/css">
      /* styles.css */

      body {
        position: relative;
        background-color: grey;
      }
      
      a {
        font-variant: petite-caps;
        font-weight: 100;
        font-size: 16px;
      }
      
      .navbar-brand {
        display: flex;
        align-items: center;
        text-decoration: none;
        color: #fff;
      }
      
      .navbar-brand img {
        width: 0px;
        height: auto;
        margin-right: 10px;
      }
      
      .sub-title {
        font-size: 0.8em;
        margin-left: 5px;
      }
      
      .logo-img {
        width: 100px;
        height: auto;
      }
      
      h2 {
        font-family: 'Alice', serif;
        color: red;
        font-size: 4.9rem;
      }
      
      p {
        font-variant: small-caps;
        color: #cecece;
      }
      
      p span {
        color: #a5a5a5;
        font-weight: bold;
      }
      
      span.icon {
        font-size: 15px;
      }
      
      .content {
        position: relative;
        height: 100vh;
      }
      
      .sub-title {
        vertical-align: -webkit-baseline-middle;
        font-size: 12px!important;
        font-family: 'Luckiest Guy', cursive;
      }
      
      .back-link {
        color: #fff;
        font-size: 2.6rem;
        font-weight: 900;
        transition: all 400ms ease-in-out;
      }
      
      .back-link:hover {
        color: #fff;
        font-size: 2.8rem;
        transition: all 400ms ease-in-out;
      }
      
      .container-centered-items {
        position: absolute;
        top: 50%;
        left: 0;
        right: 0;
      }
      
      .bg-black {
        background-color: grey;
      }
      
      .text-red {
        color: black;
      }
      
      .text-blue {
        color: black;
      }
      
      .btn-blue {
        background-color: grey;
        border-color: grey;
      }
      
      .text-black {
        color: white;
      }

    </style>

    <!--CONTENTS-->
 
    <section class="content">
            <!-- Navigation -->
                <nav class="navbar navbar-default">
                      <div class="container-fluid">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                          </button>

                          
                        
                       
                        </div>

                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                          <ul class="nav navbar-nav">
                              <img src="{% static '/img/tn.jpg' %}" alt="Tunisair Express Logo" style="width: 140px; height: 60px;">
                           
                            </ul>
                          <ul class="nav navbar-nav">
                            <li class=""><a href="https://www.tunisairexpress.net/" target="_blank">TUNISAIR Express site </a></li>
                            
                          </ul>
                          <ul class="nav navbar-nav navbar-right">
                            <li><a href="{% url 'accounts:login' %}">Se connecter</a></li>
                          </ul>
                        </div><!-- /.navbar-collapse -->
                      </div><!-- /.container-fluid -->
                </nav>
            <!-- /Naivagtion -->
           
          
            <div class="container-fluid container-centered-items bg-black">
           
              <div class="row">
              
                  <div class="col-lg-12 text-center">
                     
                      <div class="center-me-please">
                          <h1 class="text-red">Système de gestion des congés et billets à tarifs réduit</h1>
                          <p class="text-blue">Ce système vous permet de demander et gérer des congés et des billets à tarifs réduit.</p>
                          <a class="btn btn-primary btn-lg btn-blue" href="{% url 'accounts:login' %}"><span class="text-black">Se connecter</span></a>

                      </div>
                  </div>
              </div>
          </div>
          
         </div>
          
     </section> <!-- /content -->
    <div>
       {% if request.user.is_authenticated %}
                    <p style="position: absolute;bottom: 0;"><a href="{{request.META.HTTP_REFERER|escape}}" class="back-link" title="back to previous page"><i class="pe-7s-back-2"></i></a></p>
       {% endif %}
    </div>

</body>

    <!--   Core JS Files   -->
  <script src="{% static 'js/jquery.3.2.1.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
  


	<script type="text/javascript">
  
  
	</script>
 

</html>

src/templates/includes/navheader_default.html
 {% load static %}
 <nav class="navbar navbar-default navbar-fixed">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                        <span class="sr-only">Basculer la navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href=""></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-left">

                        <li>
                            <a href="" class="dropdown-toggle" data-toggle="dropdown">
                                <i class=""></i>
								<p class="hidden-lg hidden-md"></p>
                            </a>
                        </li>

                {% if request.user.is_superuser %}
                <li class="dropdown">
                    <a href="" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-bell"><span style="font-size: 14px !important; padding-left: 2px;">{{ total_admin_notifications }}</span></i>
                        <b class="caret hidden-lg hidden-md"></b>
                        <p class="hidden-lg hidden-md">
                            <b class="caret"></b>
                        </p>
                    </a>
                </li>

                {% else %}
                <li class="dropdown">
                    <a href="" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-bell"><span style="font-size: 14px !important; padding-left: 2px;">{{ total_staff_notifications }}</span></i>
                        <b class="caret hidden-lg hidden-md"></b>
                        <p class="hidden-lg hidden-md">
                            <b class="caret"></b>
                        </p>
                    </a>
                </li>
                {% endif %}

            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="" class="dropdown-toggle" data-toggle="dropdown">
                        <p>
                            <i class="fa fa-user"></i> {{ request.user}}
                            <b class="caret"></b>
                        </p>

                    </a>
                    <ul class="dropdown-menu">
                        {% if request.user.is_authenticated %}
                        <li><a href="{% url 'accounts:logout'  %}">Déconnecter</a></li>
                        {% else %}
                        <li><a href="{% url 'accounts:login'  %}">Se connecter</a></li>
                        {% endif %}
                        <li><a href="{% url 'accounts:changepassword' %}">Changer le mot de passe</a></li>
                    </ul>
                </li>
                <li class="separator hidden-lg"></li>
            </ul>
        </div>
    </div>
</nav>

                    

src/templates/includes/navheader_employee_app.html
 {% load static %}
 <nav class="navbar navbar-default navbar-fixed shadow">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                        <span class="sr-only">Basculer la navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!-- <a class="navbar-brand" href="">Dashboard </a> -->
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-left">

                        <li>
                            <a href="" class="dropdown-toggle" data-toggle="dropdown">
                                <i class=""></i>
                                <p class="hidden-lg hidden-md">Dashboard</p>
                            </a>
                        </li>

                        
                        <li class="dropdown">
                              <a href="" class="dropdown-toggle" data-toggle="dropdown">
                                    <p>
                                        Congés
                                        <b class="caret"></b>
                                    </p>

                              </a>
                              <ul class="dropdown-menu">
                                {% if request.user.is_superuser %}
                                <li><a href="{% url 'dashboard:leaveslist' %}">Congés en attente</a></li>
                                <li><a href="{% url 'dashboard:approvedleaveslist' %}">Congés acceptés</a></li>
                                <li><a href="{% url 'dashboard:canceleaveslist' %}">Congés annulés</a></li>
                                <li><a href="{% url 'dashboard:leavesrejected' %}">Congés refusés</a></li>
                                <li class="divider"></li>
                                 <li><a href="{% url 'dashboard:leaves' %}">liste des Congés </a></li>
                                {% else %}
                                <li><a href="{% url 'dashboard:createleave' %}">Demander un congé</a></li>
                                <li class="divider"></li>
                                <li><a href="{% url 'dashboard:staffleavetable' %}">Liste des congés</a></li>
                                {% endif %}
                              </ul>
                        </li>
                        
                        <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown">
                                  <p>
                                      Billets
                                      <b class="caret"></b>
                                  </p>

                            </a>
                            <ul class="dropdown-menu">
                              {% if request.user.is_superuser %}
                              <li><a href="{% url 'dashboard:ticketslist' %}"> billets en attente</a></li>
                              <li><a href="{% url 'dashboard:approvedticketslist' %}">billets acceptés</a></li>
                              <li><a href="{% url 'dashboard:ticketsrejected' %}">billets refusés</a></li>
                              <li class="divider"></li>
                              <li><a href="{% url 'dashboard:tickets' %}">liste de billets </a></li>
                              

                              {% else %}
                              <li><a href="{% url 'dashboard:createticket' %}">Demander un billet</a></li>
                              <li><a href="{% url 'dashboard:stafftickettable' %}">Liste des billets</a></li>
                              
                             

                              {% endif %}
                            </ul>
                      </li>
                      {% if request.user.is_superuser and request.user.is_staff %}
                      <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown">
                                  <p>
                                      Bénéficiaire
                                      <b class="caret"></b>
                                  </p>

                            </a>
                         <ul class="dropdown-menu">
                            <li><a href="{% url 'dashboard:beneficiairecreate' %}">Ajouter bénéficiaire</a></li>
                            <li><a href="{% url 'dashboard:beneficiaires' %}">Liste des bénéficiaires </a></li>
                         </ul>
                       </li>
                         {% endif %}    

                        {% if request.user.is_superuser and request.user.is_staff %}
                        <li class="dropdown">
                              <a href="" class="dropdown-toggle" data-toggle="dropdown">
                                    <p>
                                        Employée
                                        <b class="caret"></b>
                                    </p>

                              </a>
                              <ul class="dropdown-menu">
                                <li><a href="{% url 'dashboard:employeecreate' %}">Ajouter employé</a></li>
                                <li><a href="{% url 'dashboard:employees' %}">Liste des employés </a></li>
                                <li class="divider"></li>
                                
                                
                                <li><a href="{% url 'accounts:erasedusers' %}">les employés supprimés</a></li>
                              </ul>
                        </li>
                        {% endif %}
                       

                        
                        {% if request.user.is_superuser and request.user.is_staff %}
                        <li class="dropdown">
                              <a href="" class="dropdown-toggle" data-toggle="dropdown">
                                    <p>
                                        Utilisateurs
                                        <b class="caret"></b>
                                    </p>

                              </a>
                              <ul class="dropdown-menu">
                                <li><a href="{% url 'accounts:register' %}">Créer un utilisateur</a></li>
                                <li><a href="{% url 'accounts:users' %}">Liste des utilisateurs</a></li>
                              </ul>
                        </li>
                        {% endif %}


                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        

                        <li class="dropdown">
                              <a href="" class="dropdown-toggle refresh-page" data-toggle="dropdown" title="refresh current page">
                                    <i class="pe-7s-refresh-2"></i>
                                    <b class="hidden-lg hidden-md"></b>
                                    <p class="hidden-lg hidden-md">
                                        Actualiser
                                    
                                    </p>
                              </a>
                        </li>

                        <li class="dropdown">
                              <a href="" class="dropdown-toggle" data-toggle="dropdown">
                                    <p>
                                        <i class="fa fa-user"></i> {{ request.user}}
                                        <b class="caret"></b>
                                    </p>

                              </a>
                              <ul class="dropdown-menu">
                                {% if request.user.is_authenticated %}
                                <li><a href="{% url 'accounts:logout'  %}">Déconnecter</a></li>
                                {% else %}
                                <li><a href="{% url 'accounts:login'  %}">Se connecter</a></li>
                                {% endif %}
                                <li><a href="{% url 'accounts:changepassword' %}">Changer le mot de passe</a></li>
                                
                              </ul>
                        </li>

                        <li class="separator hidden-lg"></li>
                    </ul>
                </div>
            </div>
        </nav>